### ISSUE TITLE
[FR]: Don't symlink venv in py_binary

### ISSUE THREAD

**Issue by meowcakes** [aspect-build/rules_py#147] opened 2023-02-20 14:18 UTC
### What is the current behavior?

Currently a py_binary target will attempt to symlink its venv on execution

https://github.com/aspect-build/rules_py/blob/0bb8d01afafc9c6055c4714f756d391b21e9adcb/py/private/entry.tmpl.sh#L86-L92

### Describe the feature

This prevents deploying py_binary on a read-only filesystem. The error is also not immediately clear since the `mkdir` will fail silently, resulting in a "directory does not exist" error.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment] 2023-03-06 13:58
cc @mattem

**Comment by mattem** [comment] 2023-03-06 14:22
I think the ask here is more a duplicate of #114 and the venv used under bazel run is an intermediate format. Without bazel, you'd have the same issue on a readonly filesystem when venv attempted to create the virtual environment folder and symlink in the interpreter.

**Closed** 2023-03-06 14:22 UTC
Labels: enhancement
